api_controllers_product:
    resource: ../../src/UI/Product/Controller/Rest/
    type: annotation

api_controllers_cart:
    resource: ../../src/UI/Cart/Controller/Rest/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
